#!/bin/bash

chr() 
{
  [ "$1" -lt 256 ] || return 1
  printf "\\$(printf '%03o' "$1")"
}

ord() 
{
  LC_CTYPE=C printf '%d' "'$1"
}

seq()
{
    local ubound=${#1}
    for i in $( eval echo {0..$(( ${ubound} - 1 ))} )
    do
	echo $i
    done
}

caesar()
{
    local instr="$1"
    local rot=$2
    for i in $( seq ${instr} )
    do
	var=${instr:$i:1}
	ascii=$(ord ${var})
	local newascii=$ascii;
	if [[ ${ascii} -ge 65 ]] && [[ ${ascii} -le 90 ]]; then
	    newascii=$(( $(( $(( ${ascii} - 65 + ${rot} )) % 26 )) + 65 ))
	elif [[ ${ascii} -ge 97 ]] && [[ ${ascii} -le 122 ]]; then
	    newascii=$(( $(( $(( ${ascii} - 97 + ${rot} )) % 26 )) + 97 ))	
	fi
	chr ${newascii}
    done
    echo ""
}

if [ $# -ne 2 ]; then
    echo "Usage: caesar <filename> <rotation>"
    exit 1
fi

file=$1
rot=$2

if [ ! -f "$file" ]; then
    echo "File $file does not exist."
    exit 1
fi

data=$(<$file)
caesar "$data" $rot
