#!/bin/bash

seq() 
{
    local ubound;
    ubound="$1";
    for i in $( eval echo {1..${ubound}} )
    do
	echo ${i};
    done
}

reverse-string()
{
    local instr;
    instr="${@}";
    for i in $(seq ${#instr} )
    do
        var=${instr:$(( ${#instr} - ${i} )):1}
	if [[ "$var" == " " ]]; then
	    echo -n " "
	fi
	echo -n $var
    done
    echo " "
}

if [ $# -eq 0 ]; then
    echo "Usage: $0 <string>"
    exit 1
fi

reverse-string "${@}";
